packages:
  - apps/*
  - packages/*
allowBuilds:
  electron: true
overrides:
  "@peculiar/asn1-cms": 2.6.1
  "@peculiar/asn1-csr": 2.6.1
  "@peculiar/asn1-ecc": 2.6.1
  "@peculiar/asn1-pfx": 2.6.1
  "@peculiar/asn1-pkcs8": 2.6.1
  "@peculiar/asn1-pkcs9": 2.6.1
  "@peculiar/asn1-rsa": 2.6.1
  "@peculiar/asn1-schema": 2.6.0
  "@peculiar/asn1-x509": 2.6.1
  "@peculiar/asn1-x509-attr": 2.6.1
